baseURL: "https://cloudswarm.pages.dev/"
locale: en-us
title: "Cloudswarm"
pygmentsUseClasses: false

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: monokai

taxonomies:
  tag: tags

params:
  description: "Personal site and blog of StreamOfRon."
  social:
    - id: mastodon
      name: "Mastodon"
      url: "https://macaw.social/@streamofron"
      handle: "streamofron@macaw.social"
    - id: bluesky
      name: "Bluesky"
      url: "https://bsky.app/profile/streamofron.bsky.social"
      handle: "@streamofron.bsky.social"
    - id: github
      name: "GitHub"
      url: "https://github.com/StreamOfRon"
      handle: "@StreamOfRon"
    - id: instagram
      name: "Instagram"
      url: "https://www.instagram.com/StreamOfRon/"
      handle: "@StreamOfRon"
    - id: threads
      name: "Threads"
      url: "https://www.threads.com/@StreamOfRon"
      handle: "@StreamOfRon"
